<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            [
                'name' => 'Chaqueta Urbana Classic',
                'slug' => 'chaqueta-urbana-classic',
                'category' => 'Ropa',
                'description' => 'Chaqueta ligera para uso diario con corte moderno y tejido resistente.',
                'price' => 189900,
                'cost_price' => 98000,
                'discount_percent' => 10,
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Negro', 'Beige'],
                'stock' => 12,
                'is_featured' => true,
            ],
            [
                'name' => 'Zapatillas Runner Flex',
                'slug' => 'zapatillas-runner-flex',
                'category' => 'Zapatillas',
                'description' => 'Amortiguacion suave, suela flexible y estilo deportivo para todo el dia.',
                'price' => 249900,
                'cost_price' => 145000,
                'discount_percent' => 12,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['38', '39', '40', '41', '42'],
                'colors' => ['Blanco', 'Rojo'],
                'stock' => 18,
                'is_featured' => true,
            ],
            [
                'name' => 'Pantalon Denim Straight',
                'slug' => 'pantalon-denim-straight',
                'category' => 'Pantalones',
                'description' => 'Jean recto de tiro medio con acabado limpio y ajuste comodo.',
                'price' => 159900,
                'cost_price' => 82000,
                'discount_percent' => 0,
                'image' => 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['30', '32', '34', '36'],
                'colors' => ['Azul', 'Gris'],
                'stock' => 22,
                'is_featured' => true,
            ],
            [
                'name' => 'Buzo Minimal Soft',
                'slug' => 'buzo-minimal-soft',
                'category' => 'Ropa',
                'description' => 'Buzo suave con interior afelpado ideal para climas frescos.',
                'price' => 129900,
                'cost_price' => 64000,
                'discount_percent' => 8,
                'image' => 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Crema', 'Verde oliva'],
                'stock' => 14,
                'is_featured' => false,
            ],
            [
                'name' => 'Jogger Street Move',
                'slug' => 'jogger-street-move',
                'category' => 'Pantalones',
                'description' => 'Jogger urbano con cintura elastica y caida relajada.',
                'price' => 119900,
                'cost_price' => 58000,
                'discount_percent' => 5,
                'image' => 'https://images.unsplash.com/photo-1506629905607-bb5f7dd4f34f?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Negro', 'Gris oscuro'],
                'stock' => 16,
                'is_featured' => false,
            ],
            [
                'name' => 'Zapatillas Retro Pulse',
                'slug' => 'zapatillas-retro-pulse',
                'category' => 'Zapatillas',
                'description' => 'Silueta retro con materiales mixtos para un look autentico.',
                'price' => 279900,
                'cost_price' => 170000,
                'discount_percent' => 15,
                'image' => 'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['39', '40', '41', '42', '43'],
                'colors' => ['Azul', 'Blanco'],
                'stock' => 10,
                'is_featured' => true,
            ],
            [
                'name' => 'Camisa Oversize Linen',
                'slug' => 'camisa-oversize-linen',
                'category' => 'Ropa',
                'description' => 'Camisa amplia de textura ligera para un look fresco y elegante.',
                'price' => 149900,
                'cost_price' => 76000,
                'discount_percent' => 7,
                'image' => '/products/camisa-oversize-linen.jpg',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Blanco', 'Arena'],
                'stock' => 20,
                'is_featured' => true,
            ],
            [
                'name' => 'Polo Essential Boxy',
                'slug' => 'polo-essential-boxy',
                'category' => 'Ropa',
                'description' => 'Polo de algodon con corte boxy, suave y facil de combinar.',
                'price' => 79900,
                'cost_price' => 36000,
                'discount_percent' => 0,
                'image' => '/products/polo-essential-boxy.jpg',
                'sizes' => ['XS', 'S', 'M', 'L', 'XL'],
                'colors' => ['Negro', 'Blanco', 'Gris'],
                'stock' => 35,
                'is_featured' => false,
            ],
            [
                'name' => 'Chompa Ribbed Studio',
                'slug' => 'chompa-ribbed-studio',
                'category' => 'Ropa',
                'description' => 'Chompa acanalada de tacto suave para capas limpias de temporada.',
                'price' => 139900,
                'cost_price' => 69000,
                'discount_percent' => 6,
                'image' => '/products/chompa-ribbed-studio.jpg',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Marfil', 'Cafe'],
                'stock' => 13,
                'is_featured' => false,
            ],
            [
                'name' => 'Casaca Bomber Night',
                'slug' => 'casaca-bomber-night',
                'category' => 'Ropa',
                'description' => 'Bomber liviana con acabado urbano y bolsillos funcionales.',
                'price' => 219900,
                'cost_price' => 124000,
                'discount_percent' => 10,
                'image' => 'https://images.unsplash.com/photo-1551489186-cf8726f514f8?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Negro', 'Verde militar'],
                'stock' => 11,
                'is_featured' => true,
            ],
            [
                'name' => 'Jean Wide Leg Aura',
                'slug' => 'jean-wide-leg-aura',
                'category' => 'Pantalones',
                'description' => 'Jean wide leg con caida moderna y lavado azul medio.',
                'price' => 169900,
                'cost_price' => 88000,
                'discount_percent' => 5,
                'image' => 'https://images.unsplash.com/photo-1584370848010-d7fe6bc767ec?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['28', '30', '32', '34', '36'],
                'colors' => ['Azul claro', 'Azul oscuro'],
                'stock' => 24,
                'is_featured' => true,
            ],
            [
                'name' => 'Cargo Utility Sand',
                'slug' => 'cargo-utility-sand',
                'category' => 'Pantalones',
                'description' => 'Pantalon cargo con bolsillos amplios y silueta relajada.',
                'price' => 149900,
                'cost_price' => 78000,
                'discount_percent' => 8,
                'image' => '/products/cargo-utility-sand.jpg',
                'sizes' => ['S', 'M', 'L', 'XL'],
                'colors' => ['Arena', 'Negro'],
                'stock' => 17,
                'is_featured' => false,
            ],
            [
                'name' => 'Pantalon Tailored Flow',
                'slug' => 'pantalon-tailored-flow',
                'category' => 'Pantalones',
                'description' => 'Pantalon sastre de caida fluida para outfits pulidos y comodos.',
                'price' => 189900,
                'cost_price' => 98000,
                'discount_percent' => 0,
                'image' => 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['30', '32', '34', '36'],
                'colors' => ['Negro', 'Gris'],
                'stock' => 15,
                'is_featured' => true,
            ],
            [
                'name' => 'Short Denim Weekend',
                'slug' => 'short-denim-weekend',
                'category' => 'Pantalones',
                'description' => 'Short denim casual con acabado gastado y ajuste relajado.',
                'price' => 89900,
                'cost_price' => 42000,
                'discount_percent' => 0,
                'image' => 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['28', '30', '32', '34'],
                'colors' => ['Azul', 'Celeste'],
                'stock' => 21,
                'is_featured' => false,
            ],
            [
                'name' => 'Zapatillas Court Daily',
                'slug' => 'zapatillas-court-daily',
                'category' => 'Zapatillas',
                'description' => 'Zapatillas blancas de inspiracion court para uso diario.',
                'price' => 229900,
                'cost_price' => 132000,
                'discount_percent' => 9,
                'image' => 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['38', '39', '40', '41', '42', '43'],
                'colors' => ['Blanco', 'Crema'],
                'stock' => 19,
                'is_featured' => false,
            ],
            [
                'name' => 'Zapatillas Trek Urban',
                'slug' => 'zapatillas-trek-urban',
                'category' => 'Zapatillas',
                'description' => 'Suela robusta y mezcla de materiales para caminar con estilo.',
                'price' => 299900,
                'cost_price' => 178000,
                'discount_percent' => 11,
                'image' => 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['39', '40', '41', '42', '43'],
                'colors' => ['Negro', 'Gris'],
                'stock' => 12,
                'is_featured' => true,
            ],
            [
                'name' => 'Gorra Canvas YT',
                'slug' => 'gorra-canvas-yt',
                'category' => 'Accesorios',
                'description' => 'Gorra de lona con ajuste posterior y detalle minimalista YO-TELLO.',
                'price' => 59900,
                'cost_price' => 24000,
                'discount_percent' => 0,
                'image' => 'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['Unica'],
                'colors' => ['Negro', 'Beige'],
                'stock' => 28,
                'is_featured' => false,
            ],
            [
                'name' => 'Correa Leather Basic',
                'slug' => 'correa-leather-basic',
                'category' => 'Accesorios',
                'description' => 'Correa de acabado sobrio para elevar jeans y pantalones sastre.',
                'price' => 69900,
                'cost_price' => 31000,
                'discount_percent' => 5,
                'image' => 'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['S', 'M', 'L'],
                'colors' => ['Negro', 'Cafe'],
                'stock' => 18,
                'is_featured' => false,
            ],
            [
                'name' => 'Bolso Crossbody Noir',
                'slug' => 'bolso-crossbody-noir',
                'category' => 'Bolsos',
                'description' => 'Bolso cruzado compacto con compartimentos para uso diario.',
                'price' => 129900,
                'cost_price' => 64000,
                'discount_percent' => 6,
                'image' => 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['Unica'],
                'colors' => ['Negro'],
                'stock' => 14,
                'is_featured' => true,
            ],
            [
                'name' => 'Mochila City Compact',
                'slug' => 'mochila-city-compact',
                'category' => 'Bolsos',
                'description' => 'Mochila urbana ligera con espacio para laptop y esenciales.',
                'price' => 159900,
                'cost_price' => 82000,
                'discount_percent' => 10,
                'image' => 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=80',
                'sizes' => ['Unica'],
                'colors' => ['Negro', 'Verde'],
                'stock' => 9,
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            $category = Category::query()->where('name', $product['category'])->first();

            Product::query()->updateOrCreate(
                ['slug' => $product['slug']],
                [
                    ...$product,
                    'category_id' => $category?->id,
                ]
            );
        }
    }
}
